# archivo para configurar las dependencias que tiene el proyecto
spring.application.name=Inmobiliaria Eden

# Configuración de base de datos PostgreSQL (configuración principal)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# Puerto del servidor
server.port=9020

# Configuración alternativa para MySQL (comentada)
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://localhost:3306/inmobiliariaeden
# spring.datasource.username=nicolasDBA
# spring.datasource.password=NicolasProgramador99*

#credenciales de clave secreta para cifrado de tokens
jwt.secret=OGxqZVFLU3ZqdzdUclF4QWtoTWY3RHFjTmFnTW1GR2Y=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sendgrid.api-key=${SENDGRID_API_KEY}
sendgrid.from.email=${SENDGRID_FROM_EMAIL}
sendgrid.from.name=${SENDGRID_FROM_NAME}

#logging.level.org.springframework=DEBUG

# MailerSend : mlsn.cf21d3076ef9a56060807e919d926b4f24852b09d3f5377bdf7674dd58c65982
# rexg zxyy lquu nwvz
#


