# Etapa de build
FROM ubuntu:latest AS build

RUN apt-get update && apt-get install -y openjdk-21-jdk

WORKDIR /app

# Copiar wrapper y darle permisos
COPY mvnw .
COPY .mvn .mvn
RUN chmod +x mvnw

# Copiar pom y descargar dependencias primero (cache build)
COPY pom.xml .
RUN ./mvnw dependency:go-offline -B

# Copiar el código fuente y empaquetar
COPY src src
RUN ./mvnw clean package -DskipTests

# Etapa final (imagen ligera)
FROM eclipse-temurin:21-jre

WORKDIR /app
EXPOSE 9020

# Copiar el JAR generado (ajusta el nombre según tu pom.xml)
COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
