FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

# Copiar wrapper y configurar
COPY mvnw .
COPY .mvn .mvn
RUN chmod +x mvnw

# Copiar pom y bajar dependencias primero
COPY pom.xml .
RUN ./mvnw dependency:go-offline -B

# Copiar el resto del código y compilar
COPY src src
RUN ./mvnw clean package -DskipTests

# Imagen final
FROM eclipse-temurin:21-jre

WORKDIR /app

# Copiar el jar con nombre fijo
COPY --from=builder /app/target/app.jar app.jar

EXPOSE 9020

ENTRYPOINT ["java", "-jar", "app.jar"]