FROM eclipse-temurin:21-jdk AS builder


WORKDIR /app


COPY . .

COPY mvnw .

COPY .mvn .mvn

RUN chmod +x mvnw


RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 9020

ENTRYPOINT ["java", "-jar", "app.jar"]